language: swift
osx_image: xcode10.2

before_install:
  - make bootstrap

xcode_workspace: MusicArchive.xcworkspace 
xcode_scheme: 
  - MusicArchiveTests
xcode_destination: platform=iOS Simulator,name=iPhone Xs
